### ISSUE TITLE
TODO List (Animations)

### ISSUE THREAD

**Issue by swerdloj** [dronenb/Knot-Colorability#1]
Animations:
- [x] Animate Terms & Definitions
- [x] Historical Context
- [X] Table of Knots
- [x] Explain Invariance/Ambient Isotopy (Reidemeister Moves)
- [x] Tri-Colorability with Examples
- [ ] P-Colorability with Examples
- [ ] Touch on Alexander Polynomial
