### ISSUE TITLE
TODO Handout

### ISSUE THREAD

**Issue by swerdloj** [dronenb/Knot-Colorability#2]
Handout:

- [ ] Brief Summary of Context/Background
- [ ] In-Depth Proof/Theorem
- [ ] Multiple Exercises (Increasing Difficulty w/ Examples)
- [ ] Exercises for the Audience
- [ ] Definitions/Formulas
- [ ] Illustrations

**Comment by swerdloj** [comment]
No longer required
